apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        release: "{{ .Release.Name }}"
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      containers:
      - name: "{{ .Chart.Name }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        resources: {{ toYaml .Values.resources | nindent 10 }}
        env:
        - name: SERVER_NAME
          value: {{ .Values.config.serverName | squote }}
        - name: SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "enshrouded.passwordSecretName" . }}
              key: serverPassword
        - name: GAME_PORT
          value: {{ .Values.config.gamePort | squote }}
        - name: QUERY_PORT
          value: {{ .Values.config.queryPort | squote }}
        - name: SERVER_SLOTS
          value: {{ .Values.config.serverSlots | squote }}
        - name: EXTERNAL_CONFIG
          value: {{ .Values.config.externalConfig | squote }}
        ports:
        - name: game-port
          containerPort: {{ .Values.config.gamePort | int }}
          protocol: UDP
        - name: query-port
          containerPort: {{ .Values.config.queryPort | int }}
          protocol: UDP
        volumeMounts:
        - name: data
          mountPath: /home/steam/enshrouded/savegame
        securityContext:
          allowPrivilegeEscalation: false
          
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: "{{ .Chart.Name }}-data"
      {{- if .Values.extraVolumes }}
      {{ toYaml .Values.extraVolumes | nindent 6 }}
      {{- end }}

      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}

      {{- if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}

      {{- if .Values.initContainers }}
      initContainers: {{ toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
