apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalIPs }}
  externalIPs: {{ . | toYaml | nindent 4 }}
  {{- end }}
  ports:
  {{- if eq "LoadBalancer" .Values.service.type }}
  - name: game-port
    port: {{ .Values.config.gamePort | int }}
    targetPort: game-port
    protocol: UDP
  - name: query-port
    port: {{ .Values.config.queryPort | int }}
    targetPort: query-port
    protocol: UDP
  {{- else if eq "NodePort" .Values.service.type }}
  - name: game-port
    port: {{ .Values.config.gamePort | int }}
    targetPort: game-port
    nodePort: {{ .Values.config.gamePort | int }}
    protocol: UDP
  - name: query-port
    port: {{ .Values.config.queryPort | int }}
    targetPort: query-port
    nodePort: {{ .Values.config.queryPort | int }}
    protocol: UDP
  {{- else }}
  - name: game-port
    port: {{ .Values.config.gamePort | int }}
    targetPort: game-port
    protocol: UDP
  - name: query-port
    port: {{ .Values.config.queryPort | int }}
    targetPort: query-port
    protocol: UDP
  {{- end }}
  selector:
    app: "{{ .Chart.Name }}"
