name: Build and push Wine based image
on:
  release:
    types: [published]
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./container/wine
          file: Dockerfile
          push: true
          tags: 
            - ${{ secrets.DOCKERHUB_USERNAME }}/enshrouded-dedicated-server:wine-latest
            - ${{ secrets.DOCKERHUB_USERNAME }}/enshrouded-dedicated-server:wine-${{ github.event.release.tag_name }}
